### PR TITLE
Added Task6-Portfolio-AnushkaJain

### PR DESCRIPTION
**Pull request by anushkajain6459**
Added Task6-Portfolio-AnushkaJain

### CODE REVIEW

**Comment by ishikabansal04** [comment]
Hey . @anushkajain6459 please move your folders to the correct location i.e.
Tasks/Project_April_2021/Batch2020

**Comment by anushkajain6459** [comment]
Please check the files changed, I've made the required commits!

**Comment by ishikabansal04** [comment]
> Please check the files changed, I've made the required commits!

@anushkajain6459 you have added inside "Batch2021" but yours is "Batch2020" . Please make the changes.

**Comment by anushkajain6459** [comment]
Added to Batch2020. Please check.

**Review by ishikabansal04 — APPROVED** [review]

**Pull request merged**
