### PR TITLE
added task5 index.html

### PR DESCRIPTION
**Pull request by Kritikaparihar04**

### CODE REVIEW

**Comment by shruthi019** [comment]
Hey Kritika, please put your submission inside a folder by your name in the Task5 directory, then I'll merge this!

**Comment by Kritikaparihar04** [comment]
okay

**Comment by Kritikaparihar04** [comment]
Can you check now is it correct or not.

**Comment by shruthi019** [comment]
Great, just delete the text file 'Kritika' which is outside your folder and this is good to go! Also include the link to the deployed website in a text file inside your folder :)

**Comment by Kritikaparihar04** [comment]
Okay. I added the deployed webisite

**Review by shruthi019 — CHANGES_REQUESTED** [review]
Hey Kritika, please change the following:
1. README.md is deleted here from Task3, but it needs to be there for reference, so you can create it again (copy paste from the one which is there in the main repo)
2. In Task3, put your text file inside a folder by your name like you've done for Task5.
3. In Task5, the 'link.txt' file should also be inside your folder.

Let me know if you face any issues! :)

**Comment by Kritikaparihar04** [comment]
Okayy I will do it

**Review by shruthi019 — APPROVED** [review]

**Pull request merged**
